[package]
name = "zed_helm"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
tree-sitter-go-template = { workspace = true }
zed_extension_api = "0.0.5"