id = "helm"
name = "Helm"
description = "Syntax highlighting for Helm templates"
version = "0.0.1"
schema_version = 1
authors = ["Hemant Joshi <mail@hjoshi.me>"]
repository = "https://github.com/cabrinha/helm.zed"

[grammars.go_template]
repository = "https://github.com/ngalaiko/tree-sitter-go-template"
commit = "fe6bb984fe4f0b1661b24ff613be5163f33b2a19"